version: '3.3'  # Specifies the version of the Docker Compose file format.

services:
  # PostgreSQL database service
  postgres_server:
    image: postgres:13  # Using PostgreSQL version 13.
    environment:
      POSTGRES_DB: ${POSTGRES_DB}  # Database name from environment variable.
      POSTGRES_USER: ${POSTGRES_USER}  # User name from environment variable.
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # User password from environment variable.
    ports:
      - "5432:5432"  # Exposing PostgreSQL default port on both host and container.
    volumes:
      - ./postgres_data_car:/var/lib/postgresql/data  # Persist database data on the host.
    networks:
      - shared-network

  # pgAdmin service, a web UI for managing PostgreSQL databases
  pgadmin:
    image: dpage/pgadmin4  # Using pgAdmin 4 Docker image.
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}  # Default email to login to pgAdmin.
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}  # Default password for pgAdmin.
    ports:
      - "5050:80"  # Exposing pgAdmin on host port 5050 and container port 80.
    networks:
      - shared-network

  # Flask-based application service
  car-storage-app:
    build: .  # Builds the Docker image from Dockerfile located in '.'.
    ports:
      - "5000:5000"  # Exposing Flask's typical port 5000.
    environment:
      DATABASE_URL: ${DATABASE_URL}  # Database URL from environment variable.
    depends_on:
      - postgres_server  # Ensures PostgreSQL server starts before this application.
    networks:
      - shared-network
      
networks:
  shared-network:
    external: true